### ISSUE TITLE
Provide AVX-less users with steps to install an alternative version of Tensorflow 1.15

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3509]
This issue is a sub-task of #3227/#3361, as described by @kousu in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3361#issuecomment-887829669

> So we need to just upgrade tensorflow in the meantime, and work on doing AVX-less tensorflow builds.
> 
> We _should_ be able to do this by setting some `./configure` flags, waiting for the build to finish, and uploading the results somewhere. We can get Github Actions to do the builds, once we figure out the right flags to pick. 

TODO:

- [ ] Find a way to emulate an AVX-less environment (so that we can reproduce the "Illegal instruction" error for TF >1.6 and test around it)
- [ ] Test out Tensorflow wheels and see if they can fix the AVX error
    - [ ] Try wheels from [`fo40225/tensorflow-windows-wheel`](https://github.com/fo40225/tensorflow-windows-wheel), as described in https://stackoverflow.com/q/58198180/7584115.
    - [ ] Try compiling and distribute our own wheel. ([This blog post](https://www.eggwall.com/2020/09/compiling-tensorflow-without-avx.html) seems like a very helpful and comprehensive resource.)
- [ ] Help users install AVX-less Tensorflow wheels by either:
    - Writing a set of instructions for end users to guide them through installing the correct Tensorflow wheel, OR
    - Modifying `install_sct` to automatically install the correct Tensorflow wheel for the user, e.g.:
      ```bash
      if [[ $(python -c "import keras") == "*Illegal instruction*" ]]
      then
          echo "CPU does not appear to support AVX instruction set. Installing compiled AVX-less version of Tensorflow..."
          pip install -f https://github.com/spinalcordtoolbox/tensorflow/releases -U tensorflow
      fi
      ```

**Comment by joshuacwnewton** [comment]
>  Find a way to emulate an AVX-less environment (so that we can reproduce the "Illegal instruction" error for TF >1.6 and test around it)

The PyTorch devs made this easy for us, because they've settled on a testing setup for AVX-less machines: [Using QEMU!](https://github.com/pytorch/pytorch/issues/37786#issuecomment-625454305)

Here's what I did:

1. Installed SCT from branch [`jn/3227-test-python-3.7`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3361/files) (Tensorflow 1.15, Keras 2.3.1)
2. Installed qemu using `sudo apt-get update && sudo apt-get install -y qemu-user`
3. Ran the following to successfully reproduce AVX error:
    ```console
    > qemu-x86_64 --cpu Broadwell $SCT_DIR/python/envs/venv_sct/bin/python3 -c "import keras; print(keras.__version__)"
    qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
    [...]  # NB: There are many of these warnings... 

    Using TensorFlow backend.
    2021-08-28 14:54:33.159174: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
    ```
4. As a sanity check, I also ran the command when Tensorflow 1.5/Keras 2.1.5 was installed to make sure everything went OK.
    ```console
    > qemu-x86_64 --cpu Broadwell $SCT_DIR/python/envs/venv_sct/bin/python3 -c "import keras; print(keras.__version__)"
    qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
    [...]  # NB: There are many of these warnings... 

    Using TensorFlow backend.

    /home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    [...]  # NB: There are many of these warnings, too...

    qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
    [...]  # NB: More qemu warnings...

    2.1.5
    ```

**Comment by joshuacwnewton** [comment]
> * [ ] 2. Test out compiled AVX-less Tensorflow wheels and see if they can fix the AVX error
>     * Docker image for compiling Tensorflow (to help with the setup of the build tools): https://github.com/hadim/docker-tensorflow-builder

I'm currently testing this out. It looks like it will be very helpful for taking care of the nitpicky build environment setup steps. 

That repo is archived/unmaintained, so I've had to make a few small changes to get it to work. I'll probably end up forking this to the `spinalcordtoolbox` org, then updating it to explain how to use it to build an AVX-less Tensorflow 15.5 wheel.

I'll report back later today once it finishes (it supposedly takes a few hours).

**Comment by joshuacwnewton** [comment]
### Task 3

> - [ ] 3. Help users install AVX-less Tensorflow wheels by either:
>     - Writing a set of instructions for end users to guide them through installing the correct Tensorflow wheel, OR
>     - Modifying `install_sct` to automatically install the correct Tensorflow wheel for the user, e.g.:
>       ```bash
>       if [[ $(python -c "import keras") == "*Illegal instruction*" ]]
>       then
>           echo "CPU does not appear to support AVX instruction set. Installing compiled AVX-less version of Tensorflow..."
>           pip install -f https://github.com/spinalcordtoolbox/tensorflow/releases -U tensorflow
>       fi
>       ```

EDIT: TBD while I write out pros/cons of both choices.
