### ISSUE TITLE
Remove dependency on Keras/Tensorflow by relying only on  `onnxruntime` and ONNX models

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3735]
## Context

> The goal of this issue is similar to #3396: Convert some of SCT's deep learning models to `.ONNX` representations, then perform inference using `onnxruntime` only, in order to remove a large and difficult package dependency. Doing so would also act as a short-term alternative to:
>
> * https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3046

SCT's use of Tensorflow is just for inference (since we do our preprocessing using numpy, etc.), which sidesteps an issue that came up with PyTorch (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3396#issuecomment-844203361).

This means that we should be able to convert our TF models to `.ONNX` form, then use them as drop-in replacements, allowing us to ditch TF entirely.

## Remaining work

- `sct_deepseg_sc`
    - Centerline detection models
        - [x] dwi_ctr.h5 
        - [x] t1_ctr.h5
        - [x] t2_ctr.h5
        - [x] t2s_ctr.h5
    - 2D segmentation models
	    - [x] dwi_sc.h5
	    - [x] t1_sc.h5
	    - [X] t2_sc.h5: Success! See [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3735#issuecomment-1068110926) for details.
	    - [x] t2s_sc.h5 
    - 3D segmentation models 
	    - [x] t1_sc_3D.h5 
	    - [X] t2_sc_3D.h5 
	    - [x] t2s_sc_3D.h5 
- `sct_deepseg_gm`
    - [x] challenge_model.hdf5
    - [x] large_model.hdf5
- `sct_deepseg_lesion`
    - [x] t2_ax_lesion.h5
    - [x] t2_lesion.h5
    - [x] t2s_lesion.h5 
- [ ] Writing tests for each of these models to truly verify that the functionality is replicated _precisely_ using the .ONNX models.

**Comment by joshuacwnewton** [comment]
First, I took a look at the [`keras2onnx`](https://github.com/onnx/keras-onnx) package. But, this page has the following notice:

> We stopped active development of keras2onnx and keras2onnx is now frozen to tf-2.3 and onnx-1.10.
> 
> To convert your Keras models you can head over to [tf2onnx](https://github.com/onnx/tensorflow-onnx) which can convert Tensorflow, Keras, Tflite and Tensorflow.js models.

Despite this warning, I think we'll still need to use `keras2onnx`. Most of the documentation I've found for `tf2onnx` assumes you're using the newer bundled `tensorflow.keras`, though. So, it expects you to save the model in Tensorflow's [`SavedModel`](https://www.tensorflow.org/guide/keras/save_and_serialize#savedmodel_format) format.

But, _our_ Keras models were trained using the older Multi-Backend Keras, and were saved using the [Keras H5 format](https://www.tensorflow.org/guide/keras/save_and_serialize#keras_h5_format) instead. So, we likely want an older version of the Keras->ONNX converter, too.

----

<details>
<summary>keras2onnx steps I tried (Result: "Unknown model file format version" error)</summary>

1. `pip install keras2onnx` 
   * Result: "Successfully installed fire-0.4.0 keras2onnx-1.7.0 onnx-1.11.0 onnxconverter-common-1.9.0")
2. In PyCharm, "Debug" `test_deepseg_sc.test_deep_segmentation_spinalcord` after setting a breakpoint at this line: 
   https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2c48843be3aaa79d4e7b371f9cd0a73f55e6e7bd/spinalcordtoolbox/deepseg_sc/core.py#L355-L356
3. In an interactive console, run the following command (replacing the path with your own):
   ```python
   import keras2onnx
   onnx_model = keras2onnx.convert_keras(seg_model, 'model_1', debug_mode=1)
   keras2onnx.save_model(onnx_model, "C:\\Users\\Joshua\\repos\\spinalcordtoolbox\\data\\deepseg_sc_models\\t2_sc.onnx")
   ```

   This resulted in the following file: [t2_sc.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/8254428/t2_sc.zip)
4. Stop the debug session, then patch in the following lines of code, replacing the `seg_model.predict()` line shown above: 
    ```python
    import onnxruntime as ort
    ort_sess = ort.InferenceSession("C:\\Users\\Joshua\\repos\\spinalcordtoolbox\\data\\deepseg_sc_models\\t2_sc.onnx")
    ```
    This resulted in the following error:
    ```
    onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from C:\Users\Joshua\repos\spinalcordtoolbox\data\deepseg_sc_models\t2_sc.onnx failed:D:\a\_work\1\s\onnxruntime\core\graph\model.cc:111 onnxruntime::Model::Model Unknown model file format version.
    ```

Googling around a little suggested that this error message has to do with [a versioning issue](https://webcache.googleusercontent.com/search?q=cache:CjBZlByaPL0J:www.xavierdupre.fr/app/mlprodict/helpsphinx/i_faq.html+&cd=3&hl=en&ct=clnk&gl=ca) between ONNX packages:

> This case is due to metadata ir_version which defines the [IR_VERSION](https://github.com/onnx/onnx/blob/master/docs/IR.md#onnx-versioning) or ONNX version. When a model is machine learned model is converted, it is usually done with the default version (ir_version) returned by the [onnx](https://github.com/onnx/onnx) package. [onnxruntime](https://github.com/microsoft/onnxruntime) raises the above mentioned error message when this version (ir_version) is too recent. In this case, [onnxruntime](https://github.com/microsoft/onnxruntime) should be updated to the latest version available or the metadata ir_version can just be changed to a lower number. Th function [get_ir_version_from_onnx](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/i_faq.html#mlprodict.tools.asv_options_helper.get_ir_version_from_onnx) returns the latest tested version with mlprodict.
</details>

Given the above error, I'm going to try repeating the above steps with differing versions of `keras2onnx`, `onnxruntime`, etc.

**Comment by joshuacwnewton** [comment]
<details>
<summary>keras2onnx steps I tried (Result: "Unknown model file format version" error)</summary>

1. `pip install keras2onnx` 
   * Result: "Successfully installed fire-0.4.0 keras2onnx-1.7.0 onnx-1.11.0 onnxconverter-common-1.9.0")
2. In PyCharm, "Debug" `test_deepseg_sc.test_deep_segmentation_spinalcord` after setting a breakpoint at this line: 
   https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2c48843be3aaa79d4e7b371f9cd0a73f55e6e7bd/spinalcordtoolbox/deepseg_sc/core.py#L355-L356
3. In an interactive console, run the following command (replacing the path with your own):
   ```python
   import keras2onnx
   onnx_model = keras2onnx.convert_keras(seg_model, 'model_1', debug_mode=1)
   keras2onnx.save_model(onnx_model, "C:\\Users\\Joshua\\repos\\spinalcordtoolbox\\data\\deepseg_sc_models\\t2_sc.onnx")
   ```

   This resulted in the following file: [t2_sc.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/8254428/t2_sc.zip)
4. Stop the debug session, then patch in the following lines of code, replacing the `seg_model.predict()` line shown above: 
    ```python
    import onnxruntime as ort
    ort_sess = ort.InferenceSession("C:\\Users\\Joshua\\repos\\spinalcordtoolbox\\data\\deepseg_sc_models\\t2_sc.onnx")
    ```
    This resulted in the following error:
    ```
    onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from C:\Users\Joshua\repos\spinalcordtoolbox\data\deepseg_sc_models\t2_sc.onnx failed:D:\a\_work\1\s\onnxruntime\core\graph\model.cc:111 onnxruntime::Model::Model Unknown model file format version.
    ```

</details>

Googling around a little suggested that this error message has to do with [a versioning issue](https://webcache.googleusercontent.com/search?q=cache:CjBZlByaPL0J:www.xavierdupre.fr/app/mlprodict/helpsphinx/i_faq.html+&cd=3&hl=en&ct=clnk&gl=ca) between ONNX packages:

> This case is due to metadata ir_version which defines the [IR_VERSION](https://github.com/onnx/onnx/blob/master/docs/IR.md#onnx-versioning) or ONNX version. When a model is machine learned model is converted, it is usually done with the default version (ir_version) returned by the [onnx](https://github.com/onnx/onnx) package. [onnxruntime](https://github.com/microsoft/onnxruntime) raises the above mentioned error message when this version (ir_version) is too recent. In this case, [onnxruntime](https://github.com/microsoft/onnxruntime) should be updated to the latest version available or the metadata ir_version can just be changed to a lower number. Th function [get_ir_version_from_onnx](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/i_faq.html#mlprodict.tools.asv_options_helper.get_ir_version_from_onnx) returns the latest tested version with mlprodict.

Given the above error, I'm going to try repeating the above steps with differing versions of `keras2onnx`, `onnxruntime`, etc.
