### ISSUE TITLE
Improve our advertising for our `sct_deepseg` suite of models and tasks

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3767]
### Background

New `ivadomed` models are often quietly integrated into SCT with just a small pull request (#3766, #3637, #3527, #3224). These models are quite valuable from a developer's perspective, as they represent a (relatively) low-effort way to introduce new features for our users, without the need for large infrastructure changes. These models are also important from a lab student's perspective; they're often the culmination of an internship or research project with Ivadomed.

However, despite the value of these models, we don't really show them off as much as we could be doing:

* There usually isn't really any fanfare or advertisement alongside these PRs. We might include a small note in the changelog and the release announcement, but other than that, we don't really _do anything_ to get our users to try out the new models. 
* The biggest concern to me is that `sct_deepseg` is completely absent from our tutorials and the SCT course. (Our "Segmentation" section focuses entirely on `sct_propseg`, `sct_deepseg_sc`, and `sct_deepseg_gm`, and these functions are mostly highlighted as a preprocessing step for registration. In other words, there is no focus on our diverse range of models available for _other_ kinds of segmentation tasks.)

Right now, the main way that users would discover a given model is by reading the publication associated with the research project (if it even exists), then finding their way to SCT via the "this model is available for use in SCT" note attached to it. But, I think we could be doing better.

### Proposed solution

- [ ] Include a short section in the SCT course slides for basic usage of `sct_deepseg` (viewing tasks, selecting a task to run segmentation).
- [ ] Then, mirror these tutorial steps in our SCT Tutorials.

This would be a good start, but I think we could go even further: 

- [ ] Create a gallery for `sct_deepseg` models (similar to the example galleries from [`sklearn`](https://scikit-learn.org/stable/auto_examples/index.html) and [`skimage`](https://scikit-image.org/docs/stable/auto_examples/index.html)) that would show off the capabilities of each model. (Then, we could link to this gallery as a "Read more" at the end of the aforementioned "basic tutorial".)

However, I think that this last task would be a large undertaking, especially because of the effort required to integrate these pages with our existing documentation. (We would need to put a lot of thought into making sure the pages are discoverable, while also making sure that our website is not bloated, i.e. that it is still easy to understand and navigate).

So, if possible, I would like to see #3095 (i.e. https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3340) handled first, so that we have better infrastructure in place for navigating between "CLI Script" pages and "Tutorial" pages (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3095#issuecomment-958061803). That way, users could start at the `sct_deepseg` page, then find their way to usage examples from that page.

**Comment by jcohenadad** [comment]
> Create a gallery for sct_deepseg models

I love that

**Comment by joshuacwnewton** [comment]
I'd like to try returning to this issue, spurred on by the upcoming SCT course.

I imagine that our documentation for `sct_deepseg` will get more complex than just `sct_deepseg -h`, but regardless of where the documentation ends up, a good starting point will be having a dedicated page for just `sct_deepseg`. So, I'd like to first tackle:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3095

This is a longstanding issue that I've been wanting to implement for many years now, but haven't found a good opportunity to undertake it. But, I think now might be a good time. :)

**Comment by joshuacwnewton** [comment]
We talked about this issue once more in the latest SCT meeting, and decided that if it's possible to get a version of the model gallery ready for v6.5 (prior to the subparser refactor), we should.

I'll try to work on a quick PR for the model gallery part (plus a refactor of #4630 that only updates the `sct_deepseg` syntax).
