### ISSUE TITLE
Release checklist for SCT v6.1

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4251]
The [**6.1 release**](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues?q=is%3Aissue+is%3Aopen+milestone%3A6.1+) is set for ~~Thursday, October 12th~~ Friday, November 3rd. 

I will continually update this issue to track the ongoing state of the tasks needed before 6.1 can be released.

## Ready for review

None!

## WIP: Needs more work

None!

## Approved / Completed

- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4183
   - Merged: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4262
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4247
   - Merged: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4249 
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4228
   - Merged: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4233
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3278
   - Merged: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4235 
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4158
   - Merged: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4162
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4246
   - Merged: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4252
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4215
   - Main tasks have been done. SCT course changes will be tracked in the course-prep issue.
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4180
   - Needs second-pass review: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4250 
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4254
    - Needs review: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4268
- [x] Allow the use of `sct_download_data` in SCT course
    - Needs review: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4271

## Release checklist (@joshuacwnewton)

- [x] Manually test PyQT/matplotlib GUIs
- [x] Manually test FSLeyes plugin
- [x] Proofread merged PRs (labels, milestones, titles)
- [x] Update changelog ([plus version.txt](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4160#issuecomment-1636220309))
- [ ] Creating the release (filling in the release body text)
- [ ] Announcing the release

**Comment by joshuacwnewton** [comment]
SCT v6.1 has been released!
